dist_man1_MANS=

if BUILD_QWEERCOIND
  dist_man1_MANS+=qweercoind.1
endif

if ENABLE_QT
  dist_man1_MANS+=qweercoin-qt.1
endif

if BUILD_QWEERCOIN_CLI
  dist_man1_MANS+=qweercoin-cli.1
endif

if BUILD_QWEERCOIN_TX
  dist_man1_MANS+=qweercoin-tx.1
endif

if ENABLE_WALLET
if BUILD_QWEERCOIN_WALLET
  dist_man1_MANS+=qweercoin-wallet.1
endif
endif
