#ifndef QWEERCOIN_CHAINPARAMSSEEDS_H
#define QWEERCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the qweercoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 * No hardcoded seeds for initial launch — nodes connect via DNS seeds.
 */
#endif // QWEERCOIN_CHAINPARAMSSEEDS_H
