#!/usr/bin/env bash
#
#  qweercoind The qweercoin core server.
#
#
# chkconfig: 345 80 20
# description: qweercoind
# processname: qweercoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/qweercoind, see below
if [ -f /etc/sysconfig/qweercoind ]; then
        . /etc/sysconfig/qweercoind
fi

RETVAL=0

prog=qweercoind
# you can override the lockfile via QWEERCOIND_LOCKFILE in /etc/sysconfig/qweercoind
lockfile=${QWEERCOIND_LOCKFILE-/var/lock/subsys/qweercoind}

# qweercoind defaults to /usr/bin/qweercoind, override with QWEERCOIND_BIN
qweercoind=${QWEERCOIND_BIN-/usr/bin/qweercoind}

# qweercoind opts default to -disablewallet, override with QWEERCOIND_OPTS
qweercoind_opts=${QWEERCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $qweercoind $qweercoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
